[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "polymath-nodeos"
version = "1.1.1"
description = "A zero-dependency Autonomous Agentic Swarm Operating System."
readme = "README.md"
requires-python = ">=3.10"
license = { text = "MIT" }
authors = [
  { name="Polymath Void" },
]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.scripts]
nodeos = "polymath_nodeos.cli:main"

[tool.setuptools.packages.find]
include = ["polymath_nodeos*"]
